### ISSUE TITLE
rename rf_transp_tests.m

### ISSUE THREAD

**Issue by dlg0** [rhealbarnett/rf-transpond#2]
rename `rf_transp_tests.m` to `rf_transp_test.m` such that Matlab recognizes it as a test and you can simply run ...

```
git clone https://github.com/rhealbarnett/rf-transpond.git
cd rf-transpond
addpath(genpath('./'))
runtests
```

(also, there is your QuickStart guide written for you - and allowing you to remove the wording about adding the path in the paper text)

**Comment by rhealbarnett** [comment]
Addressed in now merged pull request.
